# Use official OpenJDK 17
FROM  eclipse-temurin:17-jdk
# Set working directory inside the container
WORKDIR /app

# Copy the jar into the container
COPY target/*.jar app.jar

# Expose the port your Spring Boot app runs on (default 8080)
EXPOSE 8080

# Run the Spring Boot app
ENTRYPOINT ["java", "-jar", "app.jar"]
